// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkJU5ZJmTHgVOWWxrKDcy2ZGH6wdqF2A',
    appId: '1:456116116150:web:d806159f65334f62b96417',
    messagingSenderId: '456116116150',
    projectId: 'glow-fe37f',
    authDomain: 'glow-fe37f.firebaseapp.com',
    storageBucket: 'glow-fe37f.appspot.com',
    measurementId: 'G-4R0SYZPSHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBAXGHOLSLzlb1A47-faO5EColRqGpKo',
    appId: '1:456116116150:android:68bdcf9a4102a382b96417',
    messagingSenderId: '456116116150',
    projectId: 'glow-fe37f',
    storageBucket: 'glow-fe37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNR0gVgwaEqPN1LRLJuK_qklgEF4JWWbg',
    appId: '1:456116116150:ios:e3fa4e0b1c2522afb96417',
    messagingSenderId: '456116116150',
    projectId: 'glow-fe37f',
    storageBucket: 'glow-fe37f.appspot.com',
    iosClientId: '456116116150-p0icgd8077nbclbni6lu7tfjc38qj3e5.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.glow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNR0gVgwaEqPN1LRLJuK_qklgEF4JWWbg',
    appId: '1:456116116150:ios:e3fa4e0b1c2522afb96417',
    messagingSenderId: '456116116150',
    projectId: 'glow-fe37f',
    storageBucket: 'glow-fe37f.appspot.com',
    iosClientId: '456116116150-p0icgd8077nbclbni6lu7tfjc38qj3e5.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.glow',
  );
}
